/*
 * Universal Video Background v2.2.0
 *
 * Copyright 2014-2023, LambertGroup
 *
*/


(function(d){function F(a,b,e){e.css({background:a.thumbsBgOffColor,"border-color":a.thumbsBorderColorOFF});e.find("img:first").css({opacity:a.thumbsBgOffImgOpacity/100,filter:"alpha(opacity="+a.thumbsBgOffImgOpacity+")"})}function I(a,b,e){e.css({background:a.thumbsBgOnColor,"border-color":a.thumbsBorderColorON});e.find("img:first").css({opacity:a.thumbsBgOnImgOpacity/100,filter:"alpha(opacity="+a.thumbsBgOnImgOpacity+")"})}function G(a,b,e,f,h,m,g,q,w,y,l,v){var t=!0;if(!e.loop&&b.current_img_no+
	a>=f||!e.loop&&0>b.current_img_no+a)t=!1;t&&(F(e,b,d(h[b.current_img_no])),N(b,e,m,y),e.randomizeVideos&&!b.bottomNavClicked?(a=Math.floor(Math.random()*f),b.current_img_no=b.current_img_no===a?Math.floor(Math.random()*f):a):b.current_img_no=b.current_img_no+a>=f?0:0>b.current_img_no+a?f-1:b.current_img_no+a,I(e,b,d(h[b.current_img_no])),q.css("left").substr(0,q.css("left").lastIndexOf("px")),0===b.current_img_no||b.current_img_no===f-1?C(0,q,l,v,e,f,g,b):C(1001,q,l,v,e,f,g,b),b.currentImg=d(w[b.current_img_no]),
	b.bottomNavClicked=!1,void 0!=b.currentImg.attr("data-youtube")&&""!=b.currentImg.attr("data-youtube")||void 0!=b.currentImg.attr("data-vimeo")&&""!=b.currentImg.attr("data-vimeo")||void 0!=b.currentImg.attr("data-selfhostedMP4")&&""!=b.currentImg.attr("data-selfhostedMP4"))&&(X(b,e,m,y,w),e.width100Proc&&e.height100Proc&&e.setAsBg&&J(b,e,w,m))}function C(a,b,e,f,h,m,g,q){var w=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?(q.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,
	left:"+="+a*q.carouselStep},600,"easeOutCubic",function(){O(q,b,e,f,h,m,g);q.isCarouselScrolling=!1})):w!=-1*Math.floor(q.current_img_no/h.numberOfThumbsPerScreen)*q.carouselStep&&(q.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:-1*Math.floor(q.current_img_no/h.numberOfThumbsPerScreen)*q.carouselStep},600,"easeOutCubic",function(){O(q,b,e,f,h,m,g);q.isCarouselScrolling=!1}))}function O(a,b,e,f,h,m,g){b=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>b?e.hasClass("carouselLeftNavDisabled")&&
	e.removeClass("carouselLeftNavDisabled"):e.addClass("carouselLeftNavDisabled");Math.abs(b-a.carouselStep)<(2*a.thumbBorderWidth+g.width()+a.thumbMarginLeft)*m?f.hasClass("carouselRightNavDisabled")&&f.removeClass("carouselRightNavDisabled"):f.addClass("carouselRightNavDisabled")}function P(a,b,e,f,h,m,g,q,w,y,l){l.height(parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10));parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)<b.thumbsWrapperMinHeight&&l.height(b.thumbsWrapperMinHeight);
	l.css({top:b.height-2*parseInt(b.borderWidth/(b.origWidth/b.width),10)-l.height()-parseInt(b.thumbsWrapperMarginTop/(b.origWidth/b.width),10)+"px",width:b.width-2*parseInt(b.borderWidth/(b.origWidth/b.width),10)+"px","padding-top":parseInt(b.thumbsWrapperTopPadding/(b.origWidth/b.width),10),"padding-bottom":parseInt(b.thumbsWrapperBottomPadding/(b.origWidth/b.width),10),"border-left":parseInt(b.borderWidth/(b.origWidth/b.width),10)+"px solid "+b.borderColor,"border-right":parseInt(b.borderWidth/(b.origWidth/
	b.width),10)+"px solid "+b.borderColor,left:-1*parseInt(b.borderWidth/(b.origWidth/b.width)+.5,10)+"px"});g.css({"background-position":"0px "+((l.height()-b.origthumbsHolderWrapperH)/2+1)+"px",height:l.height()+"px"});q.css({"background-position":"0px "+((l.height()-b.origthumbsHolderWrapperH)/2+1)+"px",height:l.height()+"px"});y.css({width:b.width-2*parseInt(b.borderWidth/(b.origWidth/b.width),10)-g.width()-q.width(),height:l.height()+"px"});b.origWidthThumbsHolderVisibleWrapper=b.origWidth-g.width()-
	q.width();h.css({width:Math.min(parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/y.width()),10),b.origThumbImgW)+"px",height:Math.min(parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/y.width()),10),b.origThumbImgH)+"px"});d(".thumbsHolder_ThumbOFF",f).find("img:first").css({width:h.width()+"px",height:h.height()+"px"});parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)<b.thumbsWrapperMinHeight?y.css({top:parseInt((l.height()-h.height())/2,10)+"px"}):y.css({top:"auto"});
	a.thumbMarginLeft=Math.floor((l.width()-g.width()-q.width()-(2*a.thumbBorderWidth+w.width())*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1));var v=-1,t;m.children().each(function(){v++;t=d(this);0>=v?t.css("margin-left",Math.floor((l.width()-g.width()-q.width()-(a.thumbMarginLeft+(2*a.thumbBorderWidth+t.width()))*(b.numberOfThumbsPerScreen-1)-(2*a.thumbBorderWidth+t.width()))/2)+"px"):t.css("margin-left",a.thumbMarginLeft+"px")});a.carouselStep=(2*a.thumbBorderWidth+w.width()+a.thumbMarginLeft)*
	b.numberOfThumbsPerScreen;if(b.numberOfThumbsPerScreen>=e)switch(b.bottomNavPos){case "left":y.css("left",b.bottomNavLateralMargin+a.thumbMarginLeft+"px");break;case "right":y.css("left",b.width-(2*a.thumbBorderWidth+h.width()+a.thumbMarginLeft)*e-b.bottomNavLateralMargin+"px");break;default:y.css("left",parseInt((l.width()-(2*a.thumbBorderWidth+w.width()+a.thumbMarginLeft)*e)/2,10)+"px")}}function J(a,b,e,f){var h=b.videoProportionWidth;void 0!=d(e[a.current_img_no]).attr("data-videoProportionWidth")&&
	""!=d(e[a.current_img_no]).attr("data-videoProportionWidth")&&(h=d(e[a.current_img_no]).attr("data-videoProportionWidth"));e=parseInt(1280/h*9,10);var m=f.parent().parent();if(b.responsiveRelativeToBrowser){b=d(window).width()+1;var g=d(window).height()}else b=f.parent().parent().parent().width(),g=f.parent().parent().parent().height(),m.css({position:"relative"});m=1/(1280/b);e/g<1280/b&&(m=1/(e/g));16!=h&&(m+=.11);a.haveYouTube&&d(".lbg_player",f).css({width:1280*m+"px",height:e*m+"px",left:parseInt((b-
	1280*m)/2,10)+"px",top:parseInt((g-e*m)/2,10)+"px"});a.haveVimeo&&d(".lbg_vimeo_player",f).css({width:1280*m+"px",height:e*m+"px",left:parseInt((b-1280*m)/2,10)+"px",top:parseInt((g-e*m)/2,10)+"px"});a.haveSelfHosted&&d("#"+a.html5_video_id).css({width:1280*m+"px",height:e*m+"px",left:parseInt((b-1280*m)/2,10)+"px",top:parseInt((g-e*m)/2,10)+"px"})}function H(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,e=RegExp("MSIE ([0-9]{1,}[.0-9]{0,})");null!=e.exec(b)&&
	(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,e=RegExp("Trident/.*rv:([0-9]{1,}[.0-9]{0,})"),null!=e.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function Q(a,b,e){var f=b.attr("data-selfhostedWEBM"),h=navigator.userAgent.toLowerCase();if(-1!=h.indexOf("chrome")||-1!=h.indexOf("msie")||-1!=h.indexOf("safari")||-1!=h.indexOf("android"))f=b.attr("data-selfhostedMP4");if(-1!=h.indexOf("ipad")||-1!=h.indexOf("iphone")||-1!=h.indexOf("ipod")||-1!=h.indexOf("webos"))f=
	b.attr("data-selfhostedMP4");-1!=h.indexOf("android")&&(f=b.attr("data-selfhostedMP4"));-1!=a&&(f=b.attr("data-selfhostedMP4"));-1!=h.indexOf("opera")&&(f=b.attr("data-selfhostedWEBM"),""!=K(e)&&(f=b.attr("data-selfhostedMP4")));-1!=h.indexOf("opr/")&&(f=b.attr("data-selfhostedWEBM"),""!=K(e)&&(f=b.attr("data-selfhostedMP4")));if(-1!=h.indexOf("firefox")||-1!=h.indexOf("mozzila"))f=b.attr("data-selfhostedWEBM"),""!=K(e)&&(f=b.attr("data-selfhostedMP4"));return f}function N(a,b,e,f){void 0!=a.currentImg.attr("data-youtube")&&
	""!=a.currentImg.attr("data-youtube")&&a.haveYouTube&&(a.player.stopVideo(),b.initialVolume=a.player.getVolume()/100,a.player.isMuted()&&(b.initialVolume=0),d(".lbg_player",e).css({"z-index":-1}));void 0!=a.currentImg.attr("data-vimeo")&&""!=a.currentImg.attr("data-vimeo")&&a.haveVimeo&&(a.vimeo_player.pause(),d(".lbg_vimeo_player",e).css({"z-index":-1}),d(".lbg_vimeo_player",e).css({"z-index":-1}),a.vimeo_player.getVolume().then(function(h){b.initialVolume=h;a.haveYouTube&&a.player.setVolume(100*
	b.initialVolume);a.haveSelfHosted&&(document.getElementById(a.html5_video_id).volume=b.initialVolume)})["catch"](function(h){}));void 0!=a.currentImg.attr("data-selfhostedMP4")&&""!=a.currentImg.attr("data-selfhostedMP4")&&a.haveSelfHosted&&(document.getElementById(a.html5_video_id).pause(),b.initialVolume=document.getElementById(a.html5_video_id).volume,document.getElementById(a.html5_video_id).muted&&(b.initialVolume=0),d("#"+a.html5_video_id).css({"z-index":-1,width:0,height:0}))}function X(a,
	b,e,f,h){b.autoPlayFirstVideo=!0;void 0!=a.currentImg.attr("data-youtube")&&""!=a.currentImg.attr("data-youtube")&&a.haveYouTube&&(e.css("background","#000000"),a.player.loadVideoById(a.currentImg.attr("data-youtube"),0,b.suggestedQuality),a.player.setVolume(100*b.initialVolume),0<b.initialVolume?a.player.unMute():a.player.mute(),d(".lbg_player",e).css({"z-index":4}));void 0!=a.currentImg.attr("data-vimeo")&&""!=a.currentImg.attr("data-vimeo")&&a.haveVimeo&&(e.css("background","#000000"),a.vimeo_player.unload(),
	a.vimeo_player.loadVideo(a.currentImg.attr("data-vimeo")).then(function(m){a.vimeo_player.setVolume(b.initialVolume);b.loop&&-1==x.indexOf("ipad")&&-1==x.indexOf("iphone")&&-1==x.indexOf("ipod")&&-1==x.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&a.vimeo_player.play()})["catch"](function(m){switch(m.name){case "TypeError":alert("the id was not a number");break;case "PasswordError":alert("password first");break;case "PrivacyError":alert("the video is password-protected or private");
	break;default:alert("some other error occurred")}}),d(".lbg_vimeo_player",e).css({"z-index":4}));void 0!=a.currentImg.attr("data-selfhostedMP4")&&""!=a.currentImg.attr("data-selfhostedMP4")&&a.haveSelfHosted&&(f=H(),e.css("background","#000000"),e=new Date,document.getElementById(a.html5_video_id).src=Q(f,a.currentImg,a.html5_video_id)+"?time="+e.getTime(),document.getElementById(a.html5_video_id).load(),d("#"+a.html5_video_id).css({"z-index":4,width:"100%",height:"100%"}),document.getElementById(a.html5_video_id).volume=
	b.initialVolume,document.getElementById(a.html5_video_id).play())}function Y(a,b){a.showTooltip&&d(".lbg_grid_tooltip").tooltip({content:function(){return d(b[d(this).attr("rel")]).attr("data-title")},position:{my:"center bottom-20",at:"center top",using:function(e,f){d(this).css(e);d("<div>").addClass("lbg_grid_arrow").addClass(f.vertical).addClass(f.horizontal).appendTo(this)}}})}var x=navigator.userAgent.toLowerCase(),K=function(a){return document.getElementById(a).canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')};
	d.fn.universal_video_background=function(a){a=d.extend({},d.fn.universal_video_background.defaults,a);return this.each(function(){var b=H(),e=d(this),f=e.parent().width(),h=e.parent().height();a.responsiveRelativeToBrowser&&(f=d(window).width(),h=d(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=f);a.origHeight=a.height;a.height100Proc&&(a.height=h);a.responsive&&(a.origWidth!=f||a.width100Proc)&&(a.width=a.origWidth>f||a.width100Proc?f:a.origWidth,a.height100Proc||(a.height=a.width/
	(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);a.width100Proc&&a.height100Proc&&(a.borderWidth=0);e.css("display","block");h=d("<div></div>").addClass("universal_video_backgroundBorder");var m=d("<div></div>").addClass("universal_video_background").addClass(a.skin);f=d('<div class="bannerControls">   <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>       </div>  ');e.wrap(m);a.texturePath&&
	(-1==b||-1!=b&&11<=b)&&(e.append('<div class="texture_over_image" />'),d(".texture_over_image",g).css({background:"url("+a.texturePath+")"}));e.after(f);var g=e.parent(".universal_video_background");a.setAsBg&&g.wrap('<div class="setAsBg" />');f=d(".bannerControls",g);g.wrap(h);var q=g.parent(".universal_video_backgroundBorder");h=d(".bottomNav",g);a.showBottomNav||h.css("display","none");a.showOnInitBottomNav||h.css("left","-5000px");var w=d(".thumbsHolderWrapper",g),y=d(".thumbsHolderVisibleWrapper",
	g),l=d(".thumbsHolder",g);var v=d('<div class="carouselLeftNav"></div>');var t=d('<div class="carouselRightNav"></div>');w.append(v);w.append(t);t.css("right","0");l.css("width",v.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||w.css({opacity:0,display:"none"});h=Math.floor(1E5*Math.random());m=d("<div></div>").addClass("lbg_player");e.append(m);var L="lbg_player"+h;d(".lbg_player",g).attr("id",L);m=d("<div></div>").addClass("lbg_vimeo_player");e.append(m);var B="lbg_vimeo_player"+h;w.css({background:a.thumbsWrapperBg});
	var r=0,c={current_img_no:0,currentImg:0,current_imgInside:"",is_very_first:!0,windowWidth:0,currentThumb:[],carouselStep:0,thumbMarginTop:0,thumbBorderWidth:0,thumbMarginLeft:0,bottomNavClicked:!1,haveYouTube:!1,haveVimeo:!1,haveSelfHosted:!1,html5_video_id:"html5_video_id_"+h,bannerRatio:a.origWidth/a.origHeight,player:!1,vimeo_player:!1,vimeo_iframe:!1,show_vimeo_controls:""};a.showVideoControls||(c.show_vimeo_controls="&amp;background=1&amp;mute=0&amp;loop=0");q.width(a.width);q.height(a.height);
	q.css("background",a.borderColor);g.width(a.width-2*a.borderWidth/(a.origWidth/a.width));g.height(a.height-2*a.borderWidth/(a.origWidth/a.width));g.css({left:a.borderWidth/(a.origWidth/a.width)+"px",top:a.borderWidth/(a.origWidth/a.width)+"px"});f.width("100%");a.centerPlugin&&q.css({margin:"0 auto"});var p=e.find("ul:first").children(),u,R="";p.each(function(){c.currentImg=d(this);c.currentImg.is("li")||(c.currentImg=c.currentImg.find("li:first"));c.currentImg.is("li")&&(c.currentImg.css("display",
	"none"),r++,void 0!=d(p[r-1]).attr("data-youtube")&&""!=d(p[r-1]).attr("data-youtube")&&(c.haveYouTube=!0),void 0!=d(p[r-1]).attr("data-vimeo")&&""!=d(p[r-1]).attr("data-vimeo")&&(c.haveVimeo=!0),void 0!=d(p[r-1]).attr("data-selfhostedMP4")&&""!=d(p[r-1]).attr("data-selfhostedMP4")&&(c.haveSelfHosted=!0),R=d(p[r-1]).attr("data-bottom-thumb"),u=d('<div class="thumbsHolder_ThumbOFF lbg_grid_tooltip" rel="'+(r-1)+'" title=""><img src="'+R+'"></div>'),u.width(a.origThumbImgW),u.height(a.origThumbImgH),
	l.append(u),F(a,c,u),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-v.width()-t.width())/(2*c.thumbBorderWidth+u.width()))-1),a.origThumbW=u.width(),a.origThumbH=u.height(),a.origthumbsHolderWrapperH=w.height(),c.thumbBorderWidth=u.css("borderLeftWidth").substr(0,u.css("borderLeftWidth").lastIndexOf("px")),c.thumbMarginLeft=Math.floor((a.width-v.width()-t.width()-(2*c.thumbBorderWidth+u.width())*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-
	1))),l.css("width",l.width()+c.thumbMarginLeft+(2*c.thumbBorderWidth+u.width())+"px"),parseInt((w.height()-parseInt(u.css("height").substring(0,u.css("height").length-2)))/2,10),l.css("height",l.height()+c.thumbMarginTop+u.height()+"px"))});var A=d(".thumbsHolder_ThumbOFF",g);v.addClass("carouselLeftNavDisabled");a.numberOfThumbsPerScreen>=r?(t.addClass("carouselRightNavDisabled"),v.css("display","none"),t.css("display","none"),w.css({"border-left":parseInt(a.borderWidth/(a.origWidth/a.width),10)+
	"px solid "+a.borderColor,"border-right":parseInt(a.borderWidth/(a.origWidth/a.width),10)+"px solid "+a.borderColor,left:-1*parseInt(a.borderWidth/(a.origWidth/a.width),10)+"px"})):y.css("left",v.width()+"px");P(c,a,r,g,A,l,v,t,u,y,w);c.current_img_no=a.firstImg;a.firstImg>r&&(c.current_img_no=r);0>a.firstImg&&(c.current_img_no=0);a.randomizeVideos&&(c.current_img_no=Math.floor(Math.random()*r));I(a,c,d(A[c.current_img_no]));if(c.haveYouTube){var S=function(n){n.data==YT.PlayerState.ENDED&&a.advanceToNextVideo&&
	(1==r&&a.loop?(c.player.seekTo(0),c.player.playVideo()):G(1,c,a,r,A,g,u,l,p,B,v,t))},T=function(n){n.target.setPlaybackQuality(a.suggestedQuality);c.player.setVolume(100*a.initialVolume);0<a.initialVolume?c.player.unMute():c.player.mute();-1!=x.indexOf("ipad")||-1!=x.indexOf("iphone")||-1!=x.indexOf("ipod")||-1!=x.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?a.autoPlayFirstVideo&&a.autoPlayOnMobile&&void 0!=d(p[c.current_img_no]).attr("data-youtube")&&""!=d(p[c.current_img_no]).attr("data-youtube")&&
	n.target.playVideo():a.autoPlayFirstVideo?void 0!=d(p[c.current_img_no]).attr("data-youtube")&&""!=d(p[c.current_img_no]).attr("data-youtube")&&n.target.playVideo():(n.target.pauseVideo(),c.player.cueVideoById(c.currentImg.attr("data-youtube")))};f=document.createElement("script");f.src=a.youtubeJsUrl;h=document.getElementsByTagName("script")[0];h.parentNode.insertBefore(f,h);window.onYouTubeIframeAPIReady=function(){var n=0;a.showVideoControls&&(n=1);void 0!=d(p[c.current_img_no]).attr("data-youtube")&&
	""!=d(p[c.current_img_no]).attr("data-youtube")?(c.player=new YT.Player(L,{width:a.width-2*a.borderWidth,height:a.height-2*a.borderWidth,videoId:d(p[c.current_img_no]).attr("data-youtube"),playerVars:{rel:0,wmode:"transparent",controls:n,showinfo:n,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,disablekb:1,playsinline:1},events:{onReady:T,onStateChange:S}}),d(".lbg_player",g).css({"z-index":3})):c.player=new YT.Player(L,{width:"100%",height:"100%",videoId:"xoORbLlFsis",playerVars:{rel:0,
	wmode:"transparent",controls:n,showinfo:n,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,disablekb:1,playsinline:1},events:{onReady:T,onStateChange:S}})}}if(c.haveVimeo){var Z=function(n){!a.advanceToNextVideo||1==r&&a.loop||G(1,c,a,r,A,g,u,l,p,B,v,t)};g.css("background","#000000");void 0!=d(p[c.current_img_no]).attr("data-vimeo")&&""!=d(p[c.current_img_no]).attr("data-vimeo")?(d(".lbg_vimeo_player",g).html('<iframe id="'+B+'" src="//player.vimeo.com/video/'+d(p[c.current_img_no]).attr("data-vimeo")+
	"?player_id="+B+c.show_vimeo_controls+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="autoplay; encrypted-media"></iframe>'),d(".lbg_vimeo_player",g).css({"z-index":0})):d(".lbg_vimeo_player",g).html('<iframe id="'+B+'" src="//player.vimeo.com/video/257707848?player_id='+B+c.show_vimeo_controls+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="autoplay; encrypted-media"></iframe>');
	c.vimeo_iframe=d("#"+B)[0];c.vimeo_player=new Vimeo.Player(c.vimeo_iframe);c.vimeo_player.ready().then(function(){c.vimeo_player.setVolume(a.initialVolume);1==r&&a.loop&&c.vimeo_player.setLoop(!0).then(function(n){})["catch"](function(n){});1<r&&!a.showVideoControls&&c.vimeo_player.setLoop(!1).then(function(n){})["catch"](function(n){});d(".lbg_vimeo_player",g).css({"z-index":0});a.autoPlayFirstVideo?void 0!=d(p[c.current_img_no]).attr("data-vimeo")&&""!=d(p[c.current_img_no]).attr("data-vimeo")&&
	-1==x.indexOf("ipad")&&-1==x.indexOf("iphone")&&-1==x.indexOf("ipod")&&-1==x.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&c.vimeo_player.play():c.vimeo_player.pause();c.vimeo_player.on("ended",Z)})}c.haveSelfHosted&&(f="",a.showVideoControls&&(f=' controls="controls"'),h="",a.autoPlayFirstVideo&&(h=' autoplay="autoplay"'),-1!=x.indexOf("ipad")||-1!=x.indexOf("iphone")||-1!=x.indexOf("ipod")||-1!=x.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?a.autoPlayOnMobile&&(h=
	" muted playsinline"):0===a.initialVolume&&(h+=' muted="muted"'),f=d('<video id="'+c.html5_video_id+'" width="100%" height="100%" preload="auto"'+f+h+"></video>"),g.append(f),d("#"+c.html5_video_id).css({"z-index":-1,width:0,height:0,position:"absolute",background:"#000000"}),document.getElementById(c.html5_video_id).volume=a.initialVolume,void 0!=d(p[c.current_img_no]).attr("data-selfhostedMP4")&&""!=d(p[c.current_img_no]).attr("data-selfhostedMP4")&&(document.getElementById(c.html5_video_id).src=
	Q(b,d(p[c.current_img_no]),c.html5_video_id),document.getElementById(c.html5_video_id).load(),d("#"+c.html5_video_id).css({"z-index":0,width:"100%",height:"100%"}),a.autoPlayFirstVideo&&document.getElementById(c.html5_video_id).play()),document.getElementById(c.html5_video_id).addEventListener("ended",function(n){a.advanceToNextVideo&&(1==r&&a.loop?document.getElementById(c.html5_video_id).play():G(1,c,a,r,A,g,u,l,p,B,v,t))},!1));a.width100Proc&&a.height100Proc&&a.setAsBg?J(c,a,p,g):(d(".lbg_player",
	g).width(g.width()),d(".lbg_player",g).height(g.height()),d(".lbg_vimeo_player",g).width(g.width()),d(".lbg_vimeo_player",g).height(g.height()));c.current_img_no>=a.numberOfThumbsPerScreen&&C(0,l,v,t,a,r,u,c);c.currentImg=d(p[c.current_img_no]);c.current_imgInside=c.currentImg.find("img:first");A.click(function(){var n=d(this).attr("rel");F(a,c,d(A[c.current_img_no]));N(c,a,g,B);c.bottomNavClicked=!0;c.current_img_no=n-1;G(1,c,a,r,A,g,u,l,p,B,v,t)});A.mouseenter(function(){var n=d(this);n.attr("rel");
	I(a,c,n)});A.mouseleave(function(){var n=d(this),k=n.attr("rel");c.current_img_no!=k&&F(a,c,n)});g.mouseenter(function(){a.autoHideBottomNav&&a.showBottomNav&&!(0>a.thumbsWrapperMarginTop&&c.isVideoPlaying)&&a.showBottomNav&&(w.css({display:"block"}),w.stop().animate({opacity:1},500,"swing",function(){}))});g.mouseleave(function(){a.autoHideBottomNav&&a.showBottomNav&&w.stop().animate({opacity:0},300,"swing",function(){})});Y(a,p);var M=!1,D=!0;d(window).resize(function(){var n=H();D=!0;-1!=n&&9==
	n&&0==c.windowWidth&&(D=!1);c.windowWidth==d(window).width()?(D=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,D=!0)):c.windowWidth=d(window).width();a.responsive&&D&&(!1!==M&&clearTimeout(M),M=setTimeout(function(){var k=a,U=r,z=g,V=u;H();if(k.width100Proc&&k.height100Proc&&!k.setAsBg){var aa=d("body").css("overflow");d("body").css("overflow","hidden")}var E=e.parent().parent().parent().parent().width(),W=e.parent().parent().parent().parent().height();
	k.responsiveRelativeToBrowser&&(E=d(window).width(),W=d(window).height());k.width100Proc&&(k.width=E);k.height100Proc&&(k.height=W);if(k.origWidth!=E||k.width100Proc)k.origWidth>E||k.width100Proc?k.width=E:k.width100Proc||(k.width=k.origWidth),k.height100Proc||(k.height=k.width/c.bannerRatio),k.width=parseInt(k.width,10),k.height=parseInt(k.height,10),q.width(k.width),q.height(k.height),z.width(parseInt(k.width-2*k.borderWidth/(k.origWidth/k.width),10)),z.height(parseInt(k.height-2*k.borderWidth/
	(k.origWidth/k.width),10)),z.css({left:k.borderWidth/(k.origWidth/k.width)+"px",top:k.borderWidth/(k.origWidth/k.width)+"px"}),k.width100Proc&&k.height100Proc&&k.setAsBg?J(c,k,p,z):(d(".lbg_player",z).width(z.width()),d(".lbg_player",z).height(z.height()),d(".lbg_vimeo_player",z).width(z.width()),d(".lbg_vimeo_player",z).height(z.height())),P(c,k,U,z,A,l,v,t,V,y,w);C(0,l,v,t,k,U,V,c);k.width100Proc&&k.height100Proc&&!k.setAsBg&&d("body").css("overflow",aa)},300))});v.click(function(){if(!c.isCarouselScrolling){var n=
	l.css("left").substr(0,l.css("left").lastIndexOf("px"));0>n&&C(1,l,v,t,a,r,u,c)}});t.click(function(){if(!c.isCarouselScrolling){var n=l.css("left").substr(0,l.css("left").lastIndexOf("px"));Math.abs(n-c.carouselStep)<(2*c.thumbBorderWidth+u.width()+c.thumbMarginLeft)*r&&C(-1,l,v,t,a,r,u,c)}})})};d.fn.universal_video_background.defaults={skin:"thumbs",width:960,height:540,width100Proc:!1,height100Proc:!1,randomizeVideos:!1,firstImg:0,initialVolume:1,loop:!0,setAsBg:!1,texturePath:"",borderWidth:0,
	borderColor:"#FFFFFF",absUrl:"",responsive:!0,responsiveRelativeToBrowser:!0,centerPlugin:!1,numberOfThumbsPerScreen:0,bottomNavPos:"center",bottomNavLateralMargin:0,thumbsWrapperMinHeight:25,thumbsWrapperMarginTop:-85,thumbsWrapperTopPadding:10,thumbsWrapperBottomPadding:10,thumbsWrapperBg:"transparent",thumbsBorderColorON:"#000000",thumbsBorderColorOFF:"#7a7a7a",thumbsBgOffColor:"#000000",thumbsBgOffImgOpacity:100,thumbsBgOnColor:"#cc181e",thumbsBgOnImgOpacity:100,showBottomNav:!0,showOnInitBottomNav:!0,
	autoHideBottomNav:!1,showVideoControls:!0,suggestedQuality:"default",autoPlayFirstVideo:!0,advanceToNextVideo:!0,autoPlayOnMobile:!1,showTooltip:!1,youtubeJsUrl:"https://www.youtube.com/iframe_api",vimeoJsUrl:"http://a.vimeocdn.com/js/froogaloop2.min.js",videoProportionWidth:16,videoProportionHeight:9,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origThumbImgW:110,origThumbImgH:65,origthumbLeftPadding:0,origthumbRightPadding:0,origthumbTopPadding:0,origthumbBottomPadding:0,origthumbTitleFont:0,
	origthumbRegFont:0,origthumbTitleLineHeight:0,origthumbRegLineHeight:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);